###
post http://localhost:3006/add
Content-Type: application/json

{
    "username":"bhagya",
    "password":"bhagya2023",
    "id":"1"
}


###
post http://localhost:3006/admin/login
Content-Type: application/json 

{
    "username":"bhagya",
    "password":"bhagya2023"
}

###
post http://localhost:3006/user/register
Content-Type: application/json 


{
    "username":"venkat",
    "email":"venkat@gmail.com",
    "password":"venkt2023",
    "address":"Hyderabad",
    "phonenumber":9888888887,
    "id":"3"
}


###
post http://localhost:3006/user/login
Content-Type: application/json 

{

    "email":"vinni@gmail.com",
    "password":"vinni2023"
 
    
}


###
get http://localhost:3006/user/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6ImphbnUyMDIyIiwiaWF0IjoxNjkxMzk2OTA3LCJleHAiOjE2OTQ5OTY5MDd9.SlHwYQMlfqiEV5Ij1OQHzTNj_eRxu8C2dN4KXa5TnE8


###
delete http://localhost:3006/delete-user/6ab5adf9-a9b8-4136-9628-4aaff19c8ebf


###
get http://localhost:3006/getOne/2457ac47-84d4-41f7-ae87-5e755157d28b



###
put http://localhost:3006/updateUser/bb0c229f-ba5c-46c3-86e2-eb750ef22841
Content-Type: application/json 

{
    "username":"viresh",
    "email":"viresh@gmail.com",
    "phonenumber":8888888888,
    "address":"hyd"
    
}

###
post http://localhost:3006/generate-invite
Content-Type: application/json

{
    "token": "abcd",
    "expiresAt":12-2-2023,
    "isUsed": false,
}