###
post http://localhost:3006/add
Content-Type: application/json

{
    "username":"bhagya",
    "password":"bhagya2023",
    "id":"1"
}


###
post http://localhost:3006/admin/login
Content-Type: application/json 

{
    "username":"bhagya",
    "password":"bhagya2023"
}

###
post http://localhost:3006/user/register
Content-Type: application/json 


{
    "username":"gagan",
    "email":"gagan@gmail.com",
    "password":"gaga2023",
    "id":"6"
}


###
post http://localhost:3006/user/login
Content-Type: application/json 

{

    "email":"gagan@gmail.com",
    "password":"gaga2023"
 
    
}


###
get http://localhost:3006/user/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXNzd29yZCI6ImphbnUyMDIyIiwiaWF0IjoxNjkxMzk2OTA3LCJleHAiOjE2OTQ5OTY5MDd9.SlHwYQMlfqiEV5Ij1OQHzTNj_eRxu8C2dN4KXa5TnE8



###
delete http://localhost:3006/delete-user/6


